### ISSUE TITLE
Cannot locate spa

### ISSUE THREAD

**Issue by DennisJohnsen** [vincedarley/homebridge-plugin-bwaspa#17]
Hey

So I'm fairly new into this Homebridge adventure, and I was so stoked to see that there was a plugin for Balboa Spa's, as I have a Spa with Wi-Fi.

My Wi-Fi module is model: **59304-H**

[I connect to it with this app](https://apps.apple.com/us/app/controlmyspa/id1193806359)
I cannot use the BWA app, I have to use this one.

![image](https://user-images.githubusercontent.com/5525386/143316323-45d9ad90-fcc1-4be8-903b-0145ad211b84.png)
This is how it appears to be setup.

Unfortunately it will not detect my spa on my local network, even if I try to type in it's direct IP or let it search the local network.
I do get different errors in debug mode, whether i type in the local IP or not.

If I put in the local IP for the Wi-Fi module
![image](https://user-images.githubusercontent.com/5525386/143316695-f58b09a5-a89f-42e7-bd39-a1c23422604f.png)

If I leave the IP config empty
![image](https://user-images.githubusercontent.com/5525386/143316897-d97c25cd-c637-4093-aeb5-8dea5d9de56f.png)
![image](https://user-images.githubusercontent.com/5525386/143316909-c7b35853-b5c5-4bed-8079-a087c70d2f96.png)

**Comment by vincedarley** [comment]
Unfortunately, there's no easy solution to this that I am aware of. It seems as if this (new?) set of hardware (Gateway Ultra, etc) from Balboa is completely different, and in particular uses a different approach for control messaging. 

There is this:  https://gitlab.com/VVlasy/controlmyspajs . This would appear to be an open-source controller that works and might work for you - but everything does a round-trip into Balboa's cloud, which is rather sad (and presumably imposes some unnecessary latency at best). And of course it is not integrated into HomeKit, homebridge, etc at all.

If there is a way to connect to the Ultra module locally on your network and send messages to it & get local replies, then I can imagine it might not be difficult to modify my plugin to work. But that is quite a big "if".  And if not, then the  route via Balboa's cloud is completely different, unfortunately.  Even Balboa chose to build an entirely new mobile app for this new hardware rather than just tweak or configure the old one.

You might want to enquire of some of the folks involved in this: https://github.com/ccutrer/balboa_worldwide_app/wiki 

Sorry not to be more helpful. I should update the documentation here to clarify this new hardware is unsupported - you are the 2nd person to get in touch in the last month.

**Comment by vincedarley** [comment]
Documentation updated. Closing this issue as unsupported at present.
