### ISSUE TITLE
Wifi Modul Crashes

### ISSUE THREAD

**Issue by dantrecht** [vincedarley/homebridge-plugin-bwaspa#3]
Unfortunately, the wifi modul crashes regularly, is not reachable then and has to be restarted at least one time per day when using your plugin. Do you know if anybody else is experiencing this problem or do you have an idea how to fix ist?

**Comment by vincedarley** [comment]
Hmm - that's not good. Let me describe what the plugin does, which might
help diagnose the problem.

On startup it connects to the Spa Wifi module, and sends something like
5-10 messages over the following few minutes to gather key data on the
Spa's configuration. It sounds as if this is NOT a problem for you.

After that the Spa's wifi module itself proactively sends state information
to this plugin every second or so. The plugin simply receives that and
passes on anything that has changed to homekit. So if this is causing the
problem, there's unfortunately nothing the plugin can do to resolve, since
it is a passive recipient.

Apart from that, every 10 minutes the plugin sends 1 message to the Spa to
check on any faults.

No other messages are sent to the Spa unless:
- You use Homebridge/Homekit/Siri/etc to control the spa - then obviously
messages are sent.
- The Spa's wifi module drops off the network/disconnects. In that case the
plugin tries to reconnect every 20 seconds or so. My own Spa does this
"occasionally" - hard to say how often, but perhaps once few days, and it
takes anywhere from a few minutes to a few hours before connection is
re-established. No idea why this happens, and given it is rare and the
plugin successfully reconnects in the end, it has not been a significant
problem for me (and, frankly, nothing I can do about it).  This process is
very visible in the homebridge log, so, worth looking for that. In my own
case I never have to manually restart the Spa.

My early googling before the creation in this plugin did show that some
people definitely have flaky wifi-modules that are always
dropping-off/crashing, and some people had even rigged up mechanisms to
automate the restart you describe. And others talked about how a "more
recent" wifi module was much more reliable. So one question to ask is what
specific wifi module you have and is it "recent" (whatever that means
exactly) vs old, and if there's anything to be done in terms of updating
the module's firmware perhaps?

Appreciate the above might not be the most helpful - is there anything that
shows up in the homebridge log (perhaps when running in debug mode) that
might help clarify?

I'm not aware of anyone else with this problem - from the plugin download
numbers there are at least hundreds of people using it, perhaps even a
thousand, and so far no other reports...

On Fri, 12 Jun 2020 at 13:15, dantrecht <notifications@github.com> wrote:
>
> Unfortunately, the wifi modul crashes regularly, is not reachable then
and has to be restarted at least one time per day when using your plugin.
Do you know if anybody else is experiencing this problem or do you have an
idea how to fix ist?

**Comment by vincedarley** [comment]
https://community.smartthings.com/t/balboa-hot-tub-wifi-module-integration/56640/116
_"I was informed that that balboa did release a wifi module version that addresses the reconnect issue. If your wifi module is 50350 -06 it is the new version that will auto reconnect. It must have the -06."_

**Comment by vincedarley** [comment]
Closed, given no response.
