### ISSUE TITLE
Fahrenheit not working

### ISSUE THREAD

**Issue by shugass** [vincedarley/homebridge-plugin-bwaspa#5]
Hello,
This plugin is awesome, thank you! I have been using it in Celsius since F wasn't working, but I see a patch was to have fixed that. I tried to switch to F, but I am getting some strange results. 
![spa](https://user-images.githubusercontent.com/67339108/87586628-cc27f000-c6ae-11ea-9332-0d0196575c5f.png)
When I change my spa to F, it stays as C on the spa tile, however the number is incorrect, it should show 38, but is showing 37.5, when I switch spa back to C, it corrects on the tile.
Note in the logs that it is reading the temp as F for current and setpoint, but is misreading the (L) target temp, that should read 80, but is showing 36 instead.
Let me know if there is anything I can test to help.
Thanks so much again for the awesome plugin!
Not sure if the screenshot will display correctly or not, but if not I will try attaching it again.

[Spa] Latest spa state Temp: 100, Target Temp(H): 100, Target Temp(L): 36, Time: 15:12, Priming: false, Heating Mode: Ready, Temp Scale: Fahrenheit, Time Scale: 12 Hr, Heating: false, Temp Range: High, Pumps: [Off Off ], Circ Pump: false, Filtering: Off, Lights: [false,], Aux: [,]

**Comment by shugass** [comment]
![ScreenShot1](https://user-images.githubusercontent.com/67339108/87586990-7738a980-c6af-11ea-906f-31c7c0f7ef23.jpg)

**Comment by vincedarley** [comment]
Thanks for the report. There's definitely a logging problem here (with that '36') that I will fix.

The other things are not so obviously problems with this plugin - homekit operates using C only as it's internal units. So my plugin must pass everything to homekit/homebridge in C - so it converts 100F to 37.77C (which is the correct conversion, not 38), and sends that to Homebridge/Homekit. That is what you are seeing in the tile: 37.7.  I'm a bit surprised by the 37.5, since I'd expect if you are using F that it would either be 37.7 (=100F) or 37.2 (=99F).

I assume you would prefer Homebridge or Homekit to display those numbers in F.  I don't know if Homebridge has a display setting for that, but Homekit I assume does. 

Hope that clears some of this up. I will fix the '36' problem which I can see is a bug in the code -- a bug that only effects the logging, not the actual functionality, but still definitely something to fix.

I'll investigate the other things, but not currently clear to me if they are bugs or not...

**Comment by shugass** [comment]
Awesome, thanks so much! I am pretty sure that a few versions ago, I was able to display in F on Homekit on my iphone, but now it won't switch to F no matter what I do (even if i change the units to F on the device config in homekit on my phone). Let me know if there is anything I can try to assist, and thanks again!

**Comment by vincedarley** [comment]
FYI: Homebridge also has a setting for C/F in "UI Settings" in the ConfigUI.

**Comment by shugass** [comment]
ah, awesome, thanks! only thing is, I'm a multi units person :( Spa in F, and Air Conditioning in C. Strange how it works out that way, not sure why it ever did....

**Comment by vincedarley** [comment]
A few minor changes in recent release should have fixed some or all of this.

**Comment by shugass** [comment]
Thanks!
